### ISSUE TITLE
[SUGGESTION] 로깅 레벨 조정 제안

### ISSUE THREAD

**Issue by DaehunGwak** [nomad-place/nomad-place-backend#10]
## 📝 설명
- 윈스턴 로깅할때 4xx status 같은 경우 interceptor 에서 warn 레벨 조정 제안

## ✅ 작업 목록
- 인터셉터를 통해 4xx warn 레벨 로깅 개발

## 🙋🏻 추가사항
> 더 하고 싶은 이야기가 있다면 들려주세요

**Comment by marshot9420** [comment]
이건 좀 개인적으로 궁금한건데요, 이런것까지 고려하는 관점은 어떻게 생겨나는 걸까요?
